#' .. content for \description{} (no empty lines) ..
#'
#' .. content for \details{} ..
#'
#' @title
#' @param path_to_data
load_dt_stroke <- function(path_to_data) {
  fread(file.path(path_to_data, 'cohort_stroke.csv')) |>
    rename(
      Year = year,
      Age = age_cat,
      Gender = bene_sex_ident_cd,
      Race = bene_race_cd,
      Pre_index_statin = bl_statin,
      Pre_index_statin_intensity = pre_potency,
      Pre_index_ezetimibe = bl_Eze,
      Pre_index_PCSK9i = bl_PCSK9i,
      Pre_index_PCSK9i_dose = bl_PCSK9i_dose,
      Pre_index_alirocumab_dose = bl_Ali_dose,
      Pre_index_alirocumab = bl_Ali,
      Pre_index_evolocumab = bl_Evo,
      Pre_index_evolocumab_dose = bl_Evo_dose,
      Pre_index_medication_number = bl_med_count,
      Pre_index_hypertension = bl_hypertsn,
      Pre_index_depression = bl_depress,
      Pre_index_diabetes = bl_diab,
      Pre_index_CKD = bl_CKD,
      Pre_index_CHD = bl_CHD,
      Pre_index_MI = bl_MI,
      Pre_index_CABG_PCI = bl_CABG,
      Pre_index_smoking = bl_smoke,
      Pre_index_cardiologist_visit = bl_cardio,
      Pre_index_HF = bl_HF,
      Pre_index_LEAD = bl_lead,
      Pre_index_ischemic_stroke = bl_Isch_stroke,
      Pre_index_ASCVD = bl_ASCVD,
      Post_index_statin_intensity = fu_potency,
      Post_index_statin = fu_statin,
      Post_index_statin_days = fu_statin_days,
      Post_index_high_intensity_statin = fu_high_statin,
      Post_index_high_intensity_statin_days = fu_high_statin_days,
      Post_index_ezetimibe = fu_Eze,
      Post_index_ezetimibe_days = fu_Eze_days,
      Post_index_PCSK9_inhibitor = fu_PCSK9i,
      Post_index_PCSK9_inhibitor_days = fu_PCSK9i_days,
      Post_index_cardiac_rehab_number = fu_cardiac_rehab_count,
      Post_index_cardiac_rehab = fu_cardiac_rehab,
      Post_index_cardiologist_visit = fu_cardio,
      Post_index_cardiologist_visit_days = fu_cardio_days,
      Post_index_neurologist_visit = fu_neuro,
      Post_index_neurologist_visit_days = fu_neuro_days,
      Post_index_outpatient_visit = fu_outpatient_visit,
      Post_index_outpatient_visit_days = fu_outpatient_visit_days,
      Post_index_any_hospitalization = fu_any_hosp,
      Post_index_any_hospitalization_days = fu_any_hosp_days,
      Post_index_CHD_hospitalization = fu_CHD,
      Post_index_CHD_hospitalization_days = fu_CHD_days,
      Post_index_MI_hospitalization = fu_MI,
      Post_index_MI_hospitalization_days = fu_MI_days,
      Post_index_HF_hospitalization = fu_HF,
      Post_index_HF_hospitalization_days = fu_HF_days,
      Post_index_ischemic_stroke_hospitalization = fu_Isch_stroke,
      Post_index_ischemic_stroke_hospitalization_days = fu_Isch_stroke_days
    ) |>
    mutate(
      Age = recode(
        Age,
        "1" = "65-69",
        "2" = "70-74",
        "3" = "75-79",
        "4" = "80-84",
        "5" = "85+"
      ),
      Gender = recode(Gender, "1" = "Male",
                      "2" = "Female"),
      Race = recode(
        Race,
        "0" = "Unknown",
        "1" = "White",
        "2" = "Black",
        "3" = "Other",
        "4" = "Asian",
        "5" = "Hispanic",
        "6" = "Native"
      ),
      Pre_index_statin = recode(Pre_index_statin,
                                "0" = "No",
                                "1" = "Yes"),
      Pre_index_statin_intensity = recode(
        Pre_index_statin_intensity,
        "3" = "High",
        "2" = "Moderate",
        "1" = "Low"
      ),
      Pre_index_statin_intensity = factor(
        Pre_index_statin_intensity,
        levels = c("Low", "Moderate", "High")
      ),
      Pre_index_ezetimibe = recode(Pre_index_ezetimibe,
                                   "0" = "No",
                                   "1" = "Yes"),
      Pre_index_PCSK9i = recode(Pre_index_PCSK9i,
                                "0" = "No",
                                "1" = "Yes"),
      Pre_index_alirocumab = recode(Pre_index_alirocumab,
                                    "0" = "No",
                                    "1" = "Yes"),
      Pre_index_evolocumab = recode(Pre_index_evolocumab,
                                    "0" = "No",
                                    "1" = "Yes"),
      Pre_index_hypertension = recode(Pre_index_hypertension,
                                      "0" = "No",
                                      "1" = "Yes"),
      Pre_index_depression = recode(Pre_index_depression,
                                    "0" = "No",
                                    "1" = "Yes"),
      Pre_index_diabetes = recode(Pre_index_diabetes,
                                  "0" = "No",
                                  "1" = "Yes"),
      Pre_index_CKD = recode(Pre_index_CKD,
                             "0" = "No",
                             "1" = "Yes"),
      Pre_index_CHD = recode(Pre_index_CHD,
                             "0" = "No",
                             "1" = "Yes"),
      Pre_index_MI = recode(Pre_index_MI,
                            "0" = "No",
                            "1" = "Yes"),
      Pre_index_CABG_PCI = recode(Pre_index_CABG_PCI,
                                  "0" = "No",
                                  "1" = "Yes"),
      Pre_index_smoking = recode(Pre_index_smoking,
                                 "0" = "No",
                                 "1" = "Yes"),
      Pre_index_cardiologist_visit = recode(
        Pre_index_cardiologist_visit,
        "0" = "No",
        "1" = "Yes"
      ),
      Pre_index_HF = recode(Pre_index_HF,
                            "0" = "No",
                            "1" = "Yes"),
      Pre_index_LEAD = recode(Pre_index_LEAD,
                              "0" = "No",
                              "1" = "Yes"),
      Pre_index_ischemic_stroke = recode(Pre_index_ischemic_stroke,
                                         "0" = "No",
                                         "1" = "Yes"),
      Pre_index_ASCVD = recode(Pre_index_ASCVD,
                               "0" = "No",
                               "1" = "Yes"),
      Post_index_cardiac_rehab = recode(Post_index_cardiac_rehab,
                                        "0" = "No",
                                        "1" = "Yes"),
      across(where(is.character), as.factor)
    )

}
